services:
  backend:
    build:
      context: ./server/src
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    env_file: .env

  mysql:
    image: mysql:latest
    container_name: mysql
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./server/src/sql-scripts:/docker-entrypoint-initdb.d
