
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/dogpark
      - PORT=3000

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    command: mongod --bind_ip_all

