export { default as Register } from "./register/Register";
export { default as SignIn } from "./signIn/signIn";
export { default as Welcome } from "./welcome/Welcome";
export { default as MyDogs } from "./mydogs/MyDogs";
export { default as DogDetails } from "./dogDetails/dogDetails";
export { default as Parks } from "./parks/Parks";
export { default as ParkDetails } from "./parkDetails/ParkDetails";
export { default as Home } from "./home/Home";
export { default as AddDog } from "./addDog/addDog";
